# Generated by Django 5.0 on 2023-12-24 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0002_alter_album_model_musician'),
        ('musician_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Musician_Model',
        ),
    ]
