# Generated by Django 5.0 on 2023-12-24 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musician_app', '0002_delete_musician_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instrument_Model',
        ),
    ]
