# Generated by Django 5.0 on 2023-12-24 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musician_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarRatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Album_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musician_app.musician_model')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album_app.starratingmodel')),
            ],
        ),
    ]
