# Generated by Django 5.0 on 2023-12-24 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0002_alter_album_model_musician'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='album_model',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='album_app.starratingmodel'),
        ),
        migrations.AddField(
            model_name='album_model',
            name='instruments',
            field=models.ManyToManyField(to='album_app.instrument_model'),
        ),
    ]
